version: '3'

services:
  database:
    image: 'mysql'
    container_name: "database_container"
    environment:
      MYSQL_ROOT_PASSWORD: bh2023
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33061:3306"

  backend:
    image: brayanprado09/tarea3
    container_name: "backend-container"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    image: brayanprado09/fronted
    container_name: "frontend-container"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data: